INSERT INTO products(
  user_id,
  name,
  price,
  photo_url,
  description,
  is_sold,
  date_posted
  )
VALUES(1, 'Canon EOS R6 with RF 15-35mm',199.99, 'https://images.unsplash.com/photo-1599664223843-9349c75196bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet justo donec enim diam vulputate ut. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Velit ut tortor pretium viverra suspendisse potenti nullam ac.' ,false,'2022-01-18' ),
      (1, 'nikon d7200', 99.00 , 'https://images.unsplash.com/photo-1614008262085-fad18b3eeef6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Est sit amet facilisis magna etiam tempor. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec.', false, '2020-04-27'),
      (1, 'NIKON D7200', 70.00,'https://images.unsplash.com/photo-1516852294404-5423eaa0d4a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80' ,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla ut morbi tincidunt augue interdum velit euismod. Nunc lobortis mattis aliquam faucibus purus in. Feugiat pretium nibh ipsum consequat.', false, '2022-05-09'),
      (2, 'Canon EOS R6 with RF 15-35mm',199.99, 'https://images.unsplash.com/photo-1599664223843-9349c75196bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet justo donec enim diam vulputate ut. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Velit ut tortor pretium viverra suspendisse potenti nullam ac.' ,false,'2022-01-18' ),
      (2, 'nikon d7200', 99.00 , 'https://images.unsplash.com/photo-1614008262085-fad18b3eeef6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Est sit amet facilisis magna etiam tempor. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec.', false, '2020-04-27'),
      (2, 'NIKON D7200', 70.00,'https://images.unsplash.com/photo-1516852294404-5423eaa0d4a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80' ,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla ut morbi tincidunt augue interdum velit euismod. Nunc lobortis mattis aliquam faucibus purus in. Feugiat pretium nibh ipsum consequat.', false, '2022-05-09'),
      (3, 'Canon EOS R6 with RF 15-35mm',199.99, 'https://images.unsplash.com/photo-1599664223843-9349c75196bc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2670&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet justo donec enim diam vulputate ut. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Velit ut tortor pretium viverra suspendisse potenti nullam ac.' ,false,'2022-01-18' ),
      (3, 'nikon d7200', 99.00 , 'https://images.unsplash.com/photo-1614008262085-fad18b3eeef6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1742&q=80','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Est sit amet facilisis magna etiam tempor. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec.', false, '2020-04-27'),
      (3, 'NIKON D7200', 70.00,'https://images.unsplash.com/photo-1516852294404-5423eaa0d4a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80' ,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla ut morbi tincidunt augue interdum velit euismod. Nunc lobortis mattis aliquam faucibus purus in. Feugiat pretium nibh ipsum consequat.', false, '2022-05-09');
