DROP TABLE IF EXISTS purchases CASCADE;

CREATE TABLE purchases (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE,
  purchase_date DATE
);